# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g6LRl4FRPI4rCXaeIPaPCcKFuWEveitr
"""

#MÓDULO 1
"""
=======================================================
MÓDULO 01 — IMPORTAÇÃO E MERGE DAS VOLATILIDADES
CORRIGIDO — sem conflitos de colunas
=======================================================
"""

import pandas as pd
import os

# -----------------------------------------------------------
# Função utilitária: padronizar e renomear colunas
# -----------------------------------------------------------

def load_sheet(path, prefix, keep_price=False):
    df = pd.read_excel(path)
    df.columns = [col.lower() for col in df.columns]
    df['data'] = pd.to_datetime(df['data'])

    # VOL REAL AGORA TEM NOME ÚNICO POR MODELO
    rename_dict = {
        'volatilidade_realizada': f'vol_real_{prefix}',
        'volatilidade_'+prefix+'_diaria': f'vol_{prefix}_dia',
        'volatilidade_'+prefix+'_1w_anualizada': f'vol_{prefix}_1w',
        'volatilidade_'+prefix+'_1m_anualizada': f'vol_{prefix}_1m',
        'volatilidade_'+prefix+'_1y_anualizada': f'vol_{prefix}_1y'
    }

    df = df.rename(columns={c: rename_dict[c] for c in rename_dict if c in df.columns})

    cols = ['data'] + list(rename_dict.values())

    if keep_price:
        cols = ['data', 'preco', 'retorno_log'] + list(rename_dict.values())

    return df[cols]

# -----------------------------------------------------------
# Função principal
# -----------------------------------------------------------

def main():

    print("\n>>> Lendo planilhas...\n")

    # Caminhos dos arquivos
    path_har     = "/content/Volatilidades_HAR_RV_1W1M1Y.xlsx"
    path_egarch  = "/content/Volatilidades_EGARCH_1W1M1Y.xlsx"
    path_gjr     = "/content/Volatilidades_GJR_1W1M1Y.xlsx"
    path_egarcht = "/content/Volatilidades_EGARCH_t_1W1M1Y.xlsx"
    path_gjrt    = "/content/Volatilidades_GJR_t_1W1M1Y.xlsx"

    df_har     = load_sheet(path_har, "har_rv", keep_price=True)   # mantém preço
    df_egarch  = load_sheet(path_egarch,  "egarch")
    df_gjr     = load_sheet(path_gjr,     "gjr")
    df_egarcht = load_sheet(path_egarcht, "egarch_t")
    df_gjrt    = load_sheet(path_gjrt,    "gjr_t")

    # ============================================================
    # 3. Merge completo por data
    # ============================================================

    df = df_har.merge(df_egarch,  on="data", how="inner")
    df = df.merge(df_gjr,     on="data", how="inner")
    df = df.merge(df_egarcht, on="data", how="inner")
    df = df.merge(df_gjrt,    on="data", how="inner")

    df = df.sort_values("data").reset_index(drop=True)

    print(df.head())

    df.to_parquet("df_vols_merged.parquet", index=False)

    print("\n>>> Arquivo salvo: df_vols_merged.parquet")
    print(">>> Módulo 01 OK!\n")

if __name__ == "__main__":
    main()

#===============================================================================

!pip install pandas pyarrow --quiet

import pandas as pd
import os

# Define the input and output file names
parquet_file_path = 'df_vols_merged.parquet'
csv_file_path = 'saida_parquet.csv'

# Read the Parquet file into a pandas DataFrame
# The 'pyarrow' engine is used by default if installed
try:
    df = pd.read_parquet(parquet_file_path, engine='pyarrow')
except ImportError:
    # Fallback to fastparquet if pyarrow is not available
    df = pd.read_parquet(parquet_file_path, engine='fastparquet')

# Convert the DataFrame to a CSV file
# index=False prevents pandas from writing the DataFrame index as a column in the CSV file
df.to_csv(csv_file_path, index=False)

print(f"Successfully converted {parquet_file_path} to {csv_file_path}")
print(f"Output file location: {os.path.abspath(csv_file_path)}")

#===============================================================================
#MÓDULO 2
"""
=======================================================
MÓDULO 02 — MONTE CARLO COM σ CONSTANTE (OPÇÃO A)
=======================================================
Projeto: Precificação de Opções com Volatilidades HAR, EGARCH,
GJR, EGARCH-t e GJR-t (σ constante por horizonte)
Autor: ChatGPT (OpenAI)
=======================================================
"""

import pandas as pd
import numpy as np
import os

# -----------------------------------------------------------
# Função Monte Carlo com σ constante
# -----------------------------------------------------------

def mc_sigma_constante(S0, K, T, sigma, r, q, n_sim=10000):
    """
    Simulador Monte Carlo (GBM risco-neutro) com σ constante.

    S0     : Preço inicial (PLD)
    K      : Strike
    T      : Tempo até o vencimento (anos)
    sigma  : Volatilidade anualizada (constante)
    r      : Taxa livre de risco
    q      : Yield/dividendo (0)
    n_sim  : Número de simulações MC
    """
    if sigma <= 0 or np.isnan(sigma):
        sigma = 1e-8  # evita problemas numéricos

    # Choques aleatórios
    Z = np.random.normal(0, 1, n_sim)

    # Simulação final
    ST = S0 * np.exp((r - q - 0.5*sigma**2)*T + sigma*np.sqrt(T)*Z)

    call = np.exp(-r*T) * np.mean(np.maximum(ST - K, 0))
    put  = np.exp(-r*T) * np.mean(np.maximum(K - ST, 0))

    return call, put

# -----------------------------------------------------------
# Função principal
# -----------------------------------------------------------

def main():

    print("\n>>> Carregando arquivo mesclado (df_vols_merged.parquet)...\n")

    df = pd.read_parquet("df_vols_merged.parquet")
    df = df.sort_values("data").reset_index(drop=True)

    # -----------------------------------------------------------
    # Configuração de parâmetros
    # -----------------------------------------------------------

    horizontes = {
        "1W": {"dias": 5,   "T": 5/252},
        "1M": {"dias": 21,  "T": 21/252},
        "1Y": {"dias": 252, "T": 252/252}
    }

    taxa_r = 0.15
    taxa_q = 0.0
    n_sim  = 10000

    resultados = []

    for idx, row in df.iterrows():
        S0 = row['preco']
        K  = S0

        for H_name, H_vals in horizontes.items():
            dias = H_vals['dias']
            T    = H_vals['T']

            # verificar existência de vencimento
            if idx + dias >= len(df):
                continue

            ST_real = df.loc[idx + dias - 1, 'preco']

            # Payoff realizado
            payoff_call = max(ST_real - K, 0)
            payoff_put  = max(K - ST_real, 0)

            # Volatilidades por modelo
            sigmas = {
                "HAR":      row[f"vol_har_rv_{H_name.lower()}"],
                "EGARCH":   row[f"vol_egarch_{H_name.lower()}"],
                "GJR":      row[f"vol_gjr_{H_name.lower()}"],
                "EGARCH-t": row[f"vol_egarch_t_{H_name.lower()}"],
                "GJR-t":    row[f"vol_gjr_t_{H_name.lower()}"],
            }

            for modelo, sigma in sigmas.items():

                call_mc, put_mc = mc_sigma_constante(
                    S0, K, T, sigma, taxa_r, taxa_q, n_sim
                )

                resultados.append({
                    "data": row["data"],
                    "horizonte": H_name,
                    "modelo": modelo,
                    "S0": S0,
                    "K": K,
                    "sigma": sigma,
                    "call_MC": call_mc,
                    "put_MC": put_mc,
                    "ST_real": ST_real,
                    "call_real": payoff_call,
                    "put_real": payoff_put,
                    "erro_call": call_mc - payoff_call,
                    "erro_put":  put_mc - payoff_put
                })

    df_res = pd.DataFrame(resultados)

    print("\n>>> Precificação concluída.")
    print(df_res.head())

    # -----------------------------------------------------------
    # Exportação final
    # -----------------------------------------------------------

    outdir = "./RESULTADOS_MC_OPCAO_A/"
    os.makedirs(outdir, exist_ok=True)

    # Exportar por ano
    print("\n>>> Gerando planilhas anuais 2019–2024...")
    for ano in range(2019, 2025):
        df_ano = df_res[df_res["data"].dt.year == ano]
        df_ano.to_excel(os.path.join(outdir, f"Opcoes_MC_Constante_{ano}.xlsx"), index=False)

    # Exportar consolidado
    df_res.to_excel(os.path.join(outdir, "Opcoes_MC_Constante_2019_2024_CONSOLIDADO.xlsx"), index=False)

    print("\n>>> Arquivos gerados em:", outdir)
    print(">>> MÓDULO 02 concluído com sucesso!\n")

# -----------------------------------------------------------
# Execução
# -----------------------------------------------------------

if __name__ == "__main__":
    main()

#MÓDULO 3
"""
=============================================================
MÓDULO 03 — MONTE CARLO COM σ DIÁRIA VARIÁVEL (DINÂMICA)
=============================================================
Projeto: Precificação de Opções com Volatilidades HAR, EGARCH,
GJR, EGARCH-t e GJR-t usando σ(t) diária.
Autor: ChatGPT (OpenAI)
=============================================================
"""

import pandas as pd
import numpy as np
import os

# -----------------------------------------------------------
# MOTOR Monte Carlo σ DINÂMICO
# -----------------------------------------------------------

def mc_sigma_dinamica(S0, K, sigmas_h, r, q, n_sim=10000):
    """
    Simulador Monte Carlo usando σ(t) variável diariamente.

    Modelo:
    S_{t+1} = S_t * exp[(r - q - 0.5*sigma_t^2)*dt + sigma_t*sqrt(dt)*Z]

    S0        : preço inicial
    K         : strike
    sigmas_h  : vetor numpy com σ diária ao longo do horizonte
    r         : taxa livre de risco anual
    q         : yield/dividendo
    n_sim     : número de simulações Monte Carlo
    """

    H = len(sigmas_h)
    dt = 1/252

    # Matriz de choques: n_sim x H
    Z = np.random.normal(0, 1, (n_sim, H))

    # Inicialização
    ST = np.full(n_sim, S0, dtype=float)

    # Simulação passo-a-passo
    for i in range(H):
        sigma_t = sigmas_h[i]
        if sigma_t <= 0 or np.isnan(sigma_t):
            sigma_t = 1e-8

        drift = (r - q - 0.5*sigma_t**2) * dt
        shock = sigma_t * np.sqrt(dt) * Z[:, i]

        ST = ST * np.exp(drift + shock)

    # Payoffs descontados
    T = H / 252
    disc = np.exp(-r * T)

    call_price = disc * np.mean(np.maximum(ST - K, 0))
    put_price  = disc * np.mean(np.maximum(K - ST, 0))

    return call_price, put_price

# -----------------------------------------------------------
# FUNÇÃO PRINCIPAL
# -----------------------------------------------------------

def main():

    print("\n>>> Carregando arquivo df_vols_merged.parquet...\n")

    # Carregar dataset unificado gerado no módulo 1
    df = pd.read_parquet("df_vols_merged.parquet")
    df = df.sort_values("data").reset_index(drop=True)

    print(">>> Dataset carregado. Total de dias:", len(df))

    # -----------------------------------------------------------
    # CONFIGURAÇÕES DO MODELO
    # -----------------------------------------------------------

    horizontes = {
        "1W": 5,
        "1M": 21,
        "1Y": 252
    }

    taxa_r = 0.15
    taxa_q = 0.0
    n_sim  = 10000

    # As volatilidades diárias
    modelos = {
      "HAR":      "vol_har_rv_dia",
      "EGARCH":   "vol_egarch_dia",
      "GJR":      "vol_gjr_dia",
      "EGARCH-t": "vol_egarch_t_dia",
      "GJR-t":    "vol_gjr_t_dia",
  }


    # -----------------------------------------------------------
    # LOOP PRINCIPAL DE PRECIFICAÇÃO
    # -----------------------------------------------------------

    print("\n>>> Iniciando precificação Monte Carlo (σ diária variável)...\n")

    resultados = []

    # iterar todos os dias possíveis
    for idx in range(len(df)):

        S0 = df.loc[idx, "preco"]
        K = S0

        for H_name, dias in horizontes.items():

            if idx + dias >= len(df):
                continue  # sem vencimento válido

            ST_real = df.loc[idx + dias - 1, "preco"]
            payoff_call = max(ST_real - K, 0)
            payoff_put  = max(K - ST_real, 0)

            # VOLATILIDADE DIÁRIA
            for modelo, col_sigma in modelos.items():

                sigmas_h = df[col_sigma].values[idx : idx + dias]

                call_mc, put_mc = mc_sigma_dinamica(
                    S0, K, sigmas_h, taxa_r, taxa_q, n_sim
                )

                resultados.append({
                    "data": df.loc[idx, "data"],
                    "horizonte": H_name,
                    "modelo": modelo,
                    "tipo_MC": "Dinamica",
                    "sigma_media": np.nanmean(sigmas_h),
                    "S0": S0,
                    "K": K,
                    "call_MC": call_mc,
                    "put_MC": put_mc,
                    "ST_real": ST_real,
                    "call_real": payoff_call,
                    "put_real": payoff_put,
                    "erro_call": call_mc - payoff_call,
                    "erro_put":  put_mc - payoff_put
                })

    # -----------------------------------------------------------
    # TRANSFORMAR EM DATAFRAME
    # -----------------------------------------------------------

    df_res = pd.DataFrame(resultados)
    print("\n>>> Precificação σ dinâmica concluída.")
    print(df_res.head())

    # -----------------------------------------------------------
    # EXPORTAÇÃO DOS RESULTADOS
    # -----------------------------------------------------------

    outdir = "./RESULTADOS_MC_OPCAO_B/"
    os.makedirs(outdir, exist_ok=True)

    print("\n>>> Exportando resultados anuais e consolidados...\n")

    for ano in range(2019, 2025):
        df_ano = df_res[df_res["data"].dt.year == ano]
        df_ano.to_excel(os.path.join(outdir, f"Opcoes_MC_Dinamica_{ano}.xlsx"), index=False)

    df_res.to_excel(os.path.join(outdir, "Opcoes_MC_Dinamica_2019_2024_CONSOLIDADO.xlsx"), index=False)

    print(">>> Arquivos salvos em:", outdir)
    print(">>> MÓDULO 03 concluído com sucesso!\n")

# -----------------------------------------------------------
# EXECUÇÃO
# -----------------------------------------------------------

if __name__ == "__main__":
    main()

#MÓDULO 4
"""
=============================================================
MÓDULO 04 — CÁLCULO DE MÉTRICAS DE ERRO
RMSE, MAE, MAPE, SMAPE para CALL e PUT
=============================================================
Projeto: Precificação de Opções (HAR, EGARCH, GJR, EGARCH-t, GJR-t)
Autor: ChatGPT (OpenAI)
=============================================================
"""

import pandas as pd
import numpy as np
import os

# -----------------------------------------------------------
# Funções matemáticas de métricas
# -----------------------------------------------------------

def calc_rmse(y_hat, y):
    return np.sqrt(np.mean((y_hat - y)**2))

def calc_mae(y_hat, y):
    return np.mean(np.abs(y_hat - y))

def calc_mape(y_hat, y):
    y_safe = np.where(y == 0, np.nan, y)
    return np.nanmean(np.abs((y_hat - y_safe) / y_safe)) * 100

def calc_smape(y_hat, y):
    return np.nanmean(2 * np.abs(y_hat - y) / (np.abs(y_hat) + np.abs(y) + 1e-8)) * 100
# -----------------------------------------------------------
# Função principal
# -----------------------------------------------------------

def main():

    print("\n>>> Lendo arquivos consolidados (Opção A + Opção B)...\n")

    dfA = pd.read_excel("./RESULTADOS_MC_OPCAO_A/Opcoes_MC_Constante_2019_2024_CONSOLIDADO.xlsx")
    dfB = pd.read_excel("./RESULTADOS_MC_OPCAO_B/Opcoes_MC_Dinamica_2019_2024_CONSOLIDADO.xlsx")

    dfA["tipo_MC"] = "Constante"
    dfB["tipo_MC"] = "Dinamica"

    df = pd.concat([dfA, dfB], ignore_index=True)
    df["Ano"] = df["data"].dt.year

    print(">>> Total de registros carregados:", len(df))

    # -----------------------------------------------------------
    # Preparar estrutura de resultados
    # -----------------------------------------------------------

    metricas = ["RMSE", "MAE", "MAPE", "SMAPE"]
    horizontes = ["1W", "1M", "1Y"]

    registros = []

    # -----------------------------------------------------------
    # Loop por ano / horizonte / modelo / tipo MC
    # -----------------------------------------------------------

    print("\n>>> Calculando métricas...\n")

    for ano in sorted(df["Ano"].unique()):

        df_ano = df[df["Ano"] == ano]

        for H in horizontes:

            df_h = df_ano[df_ano["horizonte"] == H]

            for tipo in ["Constante", "Dinamica"]:

                df_t = df_h[df_h["tipo_MC"] == tipo]

                for modelo in df_t["modelo"].unique():

                    df_m = df_t[df_t["modelo"] == modelo]

                    # series
                    call_mc = df_m["call_MC"].values
                    put_mc  = df_m["put_MC"].values
                    call_rl = df_m["call_real"].values
                    put_rl  = df_m["put_real"].values

                    # métricas
                    for met in metricas:

                        if met == "RMSE":
                            m_call = calc_rmse(call_mc, call_rl)
                            m_put  = calc_rmse(put_mc,  put_rl)
                        elif met == "MAE":
                            m_call = calc_mae(call_mc, call_rl)
                            m_put  = calc_mae(put_mc,  put_rl)
                        elif met == "MAPE":
                            m_call = calc_mape(call_mc, call_rl)
                            m_put  = calc_mape(put_mc,  put_rl)
                        elif met == "SMAPE":
                            m_call = calc_smape(call_mc, call_rl)
                            m_put  = calc_smape(put_mc,  put_rl)

                        registros.append({
                            "Ano": ano,
                            "Horizonte": H,
                            "Modelo": modelo,
                            "Tipo_MC": tipo,
                            "Métrica": met,
                            "Valor_CALL": m_call,
                            "Valor_PUT": m_put
                        })

    df_metricas = pd.DataFrame(registros)
    print("\n>>> Cálculo de métricas concluído.")
    print(df_metricas.head())

    # -----------------------------------------------------------
    # Ranking anual baseado em RMSE
    # -----------------------------------------------------------

    print("\n>>> Gerando ranking anual por RMSE...\n")

    rank_regs = []

    for ano in sorted(df_metricas["Ano"].unique()):
        for H in horizontes:
            for tipo in ["Constante", "Dinamica"]:

                df_sel = df_metricas[
                    (df_metricas["Ano"] == ano) &
                    (df_metricas["Horizonte"] == H) &
                    (df_metricas["Tipo_MC"] == tipo) &
                    (df_metricas["Métrica"] == "RMSE")
                ]

                if len(df_sel) == 0:
                    continue

                # CALL ranking
                df_call = df_sel.sort_values("Valor_CALL").reset_index(drop=True)
                # PUT ranking
                df_put  = df_sel.sort_values("Valor_PUT").reset_index(drop=True)

                rank_regs.append({
                    "Ano": ano,
                    "Horizonte": H,
                    "Tipo_MC": tipo,
                    "Melhor_Modelo_CALL": df_call.loc[0, "Modelo"],
                    "RMSE_CALL": df_call.loc[0, "Valor_CALL"],
                    "Melhor_Modelo_PUT":  df_put.loc[0, "Modelo"],
                    "RMSE_PUT":  df_put.loc[0, "Valor_PUT"]
                })

    df_rank = pd.DataFrame(rank_regs)
    print(df_rank.head())

    # -----------------------------------------------------------
    # Salvamento final
    # -----------------------------------------------------------

    outdir = "./METRICAS_MC/"
    os.makedirs(outdir, exist_ok=True)

    path_metricas = os.path.join(outdir, "Metricas_MC.xlsx")
    path_rankings = os.path.join(outdir, "Rankings_MC.xlsx")

    df_metricas.to_excel(path_metricas, index=False)
    df_rank.to_excel(path_rankings, index=False)

    print("\n>>> Arquivos gerados:")
    print("   -", path_metricas)
    print("   -", path_rankings)
    print("\n>>> MÓDULO 04 concluído com sucesso!\n")

# -----------------------------------------------------------
# Execução
# -----------------------------------------------------------

if __name__ == "__main__":
    main()

#MÓDULO 5
"""
==================================================================
MÓDULO 05 — DASHBOARD EXCEL COM SLICERS SIMULADOS
==================================================================
Gera um arquivo Excel interativo contendo:
- Tabelas (com agregações via pandas)
- Heatmap simples
==================================================================
Autor: ChatGPT (OpenAI)
==================================================================
"""
!pip install xlsxwriter --quiet
import pandas as pd
import os

def main():
    print("\n>>> Carregando arquivos de métricas...\n")

    df_metricas = pd.read_excel("./METRICAS_MC/Metricas_MC.xlsx")
    df_rank = pd.read_excel("./METRICAS_MC/Rankings_MC.xlsx")

    out_file = "./DASHBOARDS/Dashboard_Opcoes_MC.xlsx"
    os.makedirs("./DASHBOARDS", exist_ok=True)

    print(">>> Gerando Dashboard Excel...\n")

    with pd.ExcelWriter(out_file, engine="xlsxwriter") as writer:
        workbook = writer.book

        # ------------------------------------------------------------
        # Aba 1: Métricas completas
        # ------------------------------------------------------------
        df_metricas.to_excel(writer, sheet_name="Metricas", index=False)
        worksheet_m = writer.sheets["Metricas"]

        worksheet_m.add_table(0, 0, len(df_metricas), len(df_metricas.columns)-1, {
            'columns': [{'header': col} for col in df_metricas.columns],
            'style': 'Table Style Medium 9'
        })

        # ------------------------------------------------------------
        # Aba 2: Rankings
        # ------------------------------------------------------------
        df_rank.to_excel(writer, sheet_name="Rankings", index=False)
        worksheet_r = writer.sheets["Rankings"]

        worksheet_r.add_table(0, 0, len(df_rank), len(df_rank.columns)-1, {
            'columns': [{'header': col} for col in df_rank.columns],
            'style': 'Table Style Medium 9'
        })

        # ------------------------------------------------------------
        # Aba 3: Dashboard simulado com pivot via pandas
        # ------------------------------------------------------------
        # Pivot via pandas (agregando Valor_PUT por Modelo x Métrica)
        pivot_df = df_metricas.pivot_table(
            index='Modelo',
            columns='Métrica',
            values='Valor_PUT',
            aggfunc='mean'
        ).reset_index()

        pivot_df.to_excel(writer, sheet_name="Dashboard", index=False)
        ws_dash = writer.sheets["Dashboard"]

        # Criar tabela formatada
        ws_dash.add_table(0, 0, len(pivot_df), len(pivot_df.columns)-1, {
            'columns': [{'header': col} for col in pivot_df.columns],
            'style': 'Table Style Medium 9'
        })

        # Condicional: Heatmap simples
        ws_dash.conditional_format(1, 1, len(pivot_df), len(pivot_df.columns)-1, {
            'type': '3_color_scale',
            'min_color': "#63BE7B",
            'mid_color': "#FFEB84",
            'max_color': "#F8696B"
        })

        # Mensagem final
        ws_dash.write(len(pivot_df)+2, 0, "Dashboard gerado automaticamente.")
        ws_dash.write(len(pivot_df)+3, 0, "Filtros podem ser aplicados manualmente via Excel.")

    print("\n>>> Dashboard Excel criado em:", out_file)
    print(">>> MÓDULO 05 concluído.\n")

if __name__ == "__main__":
    main()

#MÓDULO 6
"""
==================================================================
MÓDULO 06 — HEATMAPS AVANÇADOS DE ERROS PARA OPÇÕES MC
==================================================================
Gera heatmaps para:
- RMSE / MAE / MAPE / SMAPE
- CALL e PUT
- Modelos × Horizontes
- Modelos × Anos
- Comparação Opção A vs Opção B
==================================================================
Autor: ChatGPT (OpenAI)
==================================================================
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

# -----------------------------------------------------------
# Função auxiliar para criar diretórios
# -----------------------------------------------------------

def criar_pasta(dirpath):
    os.makedirs(dirpath, exist_ok=True)

# -----------------------------------------------------------
# Função para gerar heatmap
# -----------------------------------------------------------

def plot_heatmap(df, row, col, val, titulo, savepath):
    plt.figure(figsize=(10, 6))
    tabela = df.pivot(index=row, columns=col, values=val)

    sns.heatmap(
        tabela,
        annot=True,
        fmt=".3f",
        cmap="RdYlGn_r",   # verde = bom, vermelho = ruim
        linewidths=.5,
        cbar_kws={'label': val}
    )
    plt.title(titulo, fontsize=14)
    plt.tight_layout()
    plt.savefig(savepath, dpi=200)
    plt.close()

# -----------------------------------------------------------
# MÓDULO PRINCIPAL
# -----------------------------------------------------------

def main():

    print("\n>>> Carregando métricas...\n")

    df_met = pd.read_excel("./METRICAS_MC/Metricas_MC.xlsx")

    # Criar pastas
    criar_pasta("./HEATMAPS_MC/")
    for m in ["RMSE", "MAE", "MAPE", "SMAPE"]:
        criar_pasta(f"./HEATMAPS_MC/{m}/")

    criar_pasta("./HEATMAPS_MC/COMPARATIVO_A_B/")

    # -----------------------------------------------------------
    # Geração dos heatmaps das métricas
    # -----------------------------------------------------------

    print(">>> Gerando heatmaps de métricas...\n")

    metricas = ["RMSE", "MAE", "MAPE", "SMAPE"]
    alvos = ["Valor_CALL", "Valor_PUT"]
    horizontes = ["1W", "1M", "1Y"]

    for metrica in metricas:

        df_m = df_met[df_met["Métrica"] == metrica]

        for alvo in alvos:

            # Heatmap Modelo × Horizonte (todos anos agregados)
            df_grp = df_m.groupby(["Modelo", "Horizonte"]) \
                         [alvo].mean().reset_index()

            savepath = f"./HEATMAPS_MC/{metrica}/{metrica}_{alvo}_Modelo_Horizonte.png"

            plot_heatmap(
                df_grp,
                row="Modelo",
                col="Horizonte",
                val=alvo,
                titulo=f"{metrica} — {alvo} (Média 2019–2024)",
                savepath=savepath
            )

            # Heatmap Modelo × Ano para cada horizonte
            for H in horizontes:

                df_h = df_m[df_m["Horizonte"] == H]

                df_grp2 = df_h.groupby(["Modelo", "Ano"])[alvo].mean().reset_index()

                savepath2 = f"./HEATMAPS_MC/{metrica}/{metrica}_{alvo}_Modelo_Ano_{H}.png"

                plot_heatmap(
                    df_grp2,
                    row="Modelo",
                    col="Ano",
                    val=alvo,
                    titulo=f"{metrica} — {alvo} ({H})",
                    savepath=savepath2
                )

    # -----------------------------------------------------------
    # COMPARATIVO OPÇÃO A vs B
    # -----------------------------------------------------------

    print(">>> Gerando heatmaps comparativos A vs B...\n")

    dfA = pd.read_excel("./RESULTADOS_MC_OPCAO_A/Opcoes_MC_Constante_2019_2024_CONSOLIDADO.xlsx")
    dfB = pd.read_excel("./RESULTADOS_MC_OPCAO_B/Opcoes_MC_Dinamica_2019_2024_CONSOLIDADO.xlsx")

    dfA["tipo_MC"] = "A"
    dfB["tipo_MC"] = "B"

    df_merged = dfA.merge(
        dfB,
        on=["data", "horizonte", "modelo"],
        suffixes=("_A", "_B")
    )

    # Erros comparativos (A - B)
    df_merged["RMSE_CALL_A"] = (df_merged["erro_call_A"]**2)
    df_merged["RMSE_PUT_A"]  = (df_merged["erro_put_A"]**2)
    df_merged["RMSE_CALL_B"] = (df_merged["erro_call_B"]**2)
    df_merged["RMSE_PUT_B"]  = (df_merged["erro_put_B"]**2)

    df_comp = df_merged.groupby(["modelo", "horizonte"]).agg({
        "RMSE_CALL_A": "mean",
        "RMSE_CALL_B": "mean",
        "RMSE_PUT_A":  "mean",
        "RMSE_PUT_B":  "mean"
    }).reset_index()

    df_comp["Delta_CALL"] = df_comp["RMSE_CALL_A"] - df_comp["RMSE_CALL_B"]
    df_comp["Delta_PUT"]  = df_comp["RMSE_PUT_A"]  - df_comp["RMSE_PUT_B"]

    # Heatmap CALL A - B
    plot_heatmap(
        df_comp,
        row="modelo",
        col="horizonte",
        val="Delta_CALL",
        titulo="Diferença A – B (RMSE CALL)",
        savepath="./HEATMAPS_MC/COMPARATIVO_A_B/Heatmap_Delta_CALL_A_B.png"
    )

    # Heatmap PUT A - B
    plot_heatmap(
        df_comp,
        row="modelo",
        col="horizonte",
        val="Delta_PUT",
        titulo="Diferença A – B (RMSE PUT)",
        savepath="./HEATMAPS_MC/COMPARATIVO_A_B/Heatmap_Delta_PUT_A_B.png"
    )

    print("\n>>> Heatmaps salvos em: /HEATMAPS_MC/")
    print(">>> MÓDULO 06 concluído com sucesso!\n")

# -----------------------------------------------------------
# Execução
# -----------------------------------------------------------

if __name__ == "__main__":
    main()

#MÓDULO 7
"""
==================================================================
MÓDULO 07 — CORRELAÇÃO ENTRE ERRO DE σ E ERRO DAS OPÇÕES MC
==================================================================
Calcula, para cada modelo/horizonte/tipo_MC:

- Volatilidade realizada no horizonte (anualizada)
- Erro de sigma: sigma_modelo - sigma_real
- Correlação Pearson entre erro_sigma e erro_call/erro_put
- Gera scatterplots erro_sigma × erro_call / erro_put

Arquivos de entrada:
- df_vols_merged.parquet
- RESULTADOS_MC_OPCAO_A/Opcoes_MC_Constante_2019_2024_CONSOLIDADO.xlsx
- RESULTADOS_MC_OPCAO_B/Opcoes_MC_Dinamica_2019_2024_CONSOLIDADO.xlsx

Saídas:
- ./CORRELACAO_SIGMA/Correlacoes_sigma_erros.csv
- ./CORRELACAO_SIGMA/SCATTERS/*.png
==================================================================
Autor: ChatGPT (OpenAI)
==================================================================
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

# -----------------------------------------------------------
# Funções auxiliares
# -----------------------------------------------------------

def criar_pasta(path):
    os.makedirs(path, exist_ok=True)

def corr_pearson(x, y):
    """Correlação Pearson simples, ignorando NaNs."""
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    mask = ~np.isnan(x) & ~np.isnan(y)
    if mask.sum() < 2:
        return np.nan
    return np.corrcoef(x[mask], y[mask])[0, 1]

# -----------------------------------------------------------
# Função para calcular sigma realizada anualizada por modelo
# -----------------------------------------------------------
def calc_sigma_real_h(df_vols, idx_ini, H):
    """
    Calcula a volatilidade realizada anualizada no horizonte H
    usando retornos log observados (independente do modelo).
    """
    if idx_ini + H > len(df_vols):
        return np.nan

    rets = df_vols["retorno_log"].values[idx_ini : idx_ini + H]
    var = np.sum(rets**2)
    sigma_periodo = np.sqrt(var)
    sigma_anual = sigma_periodo * np.sqrt(252 / H)
    return sigma_anual


# -----------------------------------------------------------
# MÓDULO PRINCIPAL
# -----------------------------------------------------------

def main():

    print("\n>>> Carregando df_vols_merged.parquet e resultados MC A/B...\n")

    # Base de preços/retornos
    df_vols = pd.read_parquet("df_vols_merged.parquet").sort_values("data").reset_index(drop=True)

    # Resultados MC A (σ constante) e B (σ dinâmica)
    dfA = pd.read_excel("./RESULTADOS_MC_OPCAO_A/Opcoes_MC_Constante_2019_2024_CONSOLIDADO.xlsx")
    dfB = pd.read_excel("./RESULTADOS_MC_OPCAO_B/Opcoes_MC_Dinamica_2019_2024_CONSOLIDADO.xlsx")

    dfA["tipo_MC"] = "Constante"
    dfB["tipo_MC"] = "Dinamica"

    # Para facilitar o join com df_vols, garantimos tipo datetime
    dfA["data"] = pd.to_datetime(dfA["data"])
    dfB["data"] = pd.to_datetime(dfB["data"])
    df_vols["data"] = pd.to_datetime(df_vols["data"])

    # Concatenar resultados MC
    df_mc = pd.concat([dfA, dfB], ignore_index=True)
    df_mc = df_mc.sort_values("data").reset_index(drop=True)

    print("Total de registros de opções MC:", len(df_mc))

    # Map de horizontes em dias úteis
    H_map = {"1W": 5, "1M": 21, "1Y": 252}

    # Vamos criar um DataFrame com:
    # data, horizonte, modelo, tipo_MC, sigma_modelo, sigma_real, erro_sigma, erro_call, erro_put
    registros = []

    # Índice da base de vols por data para localização rápida
    df_vols = df_vols.reset_index().rename(columns={"index": "idx_vol"})
    # Fazemos merge df_mc com df_vols pela data para saber o idx_ini de cada contrato
    df_join = df_mc.merge(df_vols[["idx_vol", "data"]], on="data", how="left")

    print("\n>>> Calculando sigma_real e erro_sigma para cada contrato...\n")

    for i, row in df_join.iterrows():
        idx_ini = int(row["idx_vol"])
        H_name = row["horizonte"]
        modelo = row["modelo"]
        tipo   = row["tipo_MC"]

        if H_name not in H_map:
            continue
        H = H_map[H_name]

        # sigma_realizada anualizada no horizonte
        sigma_real = calc_sigma_real_h(df_vols, idx_ini, H)

        # sigma do modelo:
        if tipo == "Constante":
            sigma_modelo = row["sigma_usada"] if "sigma_usada" in row.index else np.nan
        else:
            # Dinâmica: usamos sigma_media (já calculada no módulo 3)
            sigma_modelo = row["sigma_media"] if "sigma_media" in row.index else np.nan

        erro_sigma = sigma_modelo - sigma_real

        registros.append({
            "data": row["data"],
            "horizonte": H_name,
            "modelo": modelo,
            "tipo_MC": tipo,
            "sigma_modelo": sigma_modelo,
            "sigma_real": sigma_real,
            "erro_sigma": erro_sigma,
            "erro_call": row["erro_call"],
            "erro_put":  row["erro_put"]
        })

    df_corr_base = pd.DataFrame(registros)

    print("Exemplo da base de correlação erro_sigma × erros opções:")
    print(df_corr_base.head())

    # -----------------------------------------------------------
    # Cálculo das correlações agrupadas
    # -----------------------------------------------------------

    print("\n>>> Calculando correlações por modelo/horizonte/tipo_MC...\n")

    grupos = df_corr_base.groupby(["modelo", "horizonte", "tipo_MC"])

    registros_corr = []

    for (modelo, H_name, tipo), grp in grupos:

        corr_call = corr_pearson(grp["erro_sigma"], grp["erro_call"])
        corr_put  = corr_pearson(grp["erro_sigma"], grp["erro_put"])

        registros_corr.append({
            "modelo": modelo,
            "horizonte": H_name,
            "tipo_MC": tipo,
            "corr_erro_sigma__erro_CALL": corr_call,
            "corr_erro_sigma__erro_PUT":  corr_put,
            "n_obs": len(grp)
        })

    df_correl = pd.DataFrame(registros_corr)
    print(df_correl)

    # -----------------------------------------------------------
    # Salvar correlações em CSV
    # -----------------------------------------------------------

    outdir = "./CORRELACAO_SIGMA/"
    scatter_dir = "./CORRELACAO_SIGMA/SCATTERS/"
    criar_pasta(outdir)
    criar_pasta(scatter_dir)

    path_corr = os.path.join(outdir, "Correlacoes_sigma_erros.csv")
    df_correl.to_csv(path_corr, index=False)

    print("\n>>> Tabela de correlações salva em:", path_corr)

    # -----------------------------------------------------------
    # Gerar scatterplots erro_sigma × erro_CALL / erro_PUT
    # -----------------------------------------------------------

    print("\n>>> Gerando scatterplots erro_sigma × erro_CALL/PUT...\n")

    for (modelo, H_name, tipo), grp in grupos:

        if len(grp) < 5:
            continue  # poucos pontos, ignora

        # Scatter para CALL
        plt.figure(figsize=(6,4))
        plt.scatter(grp["erro_sigma"], grp["erro_call"], alpha=0.5)
        plt.axhline(0, color='gray', linewidth=0.8)
        plt.axvline(0, color='gray', linewidth=0.8)
        plt.title(f"Erro σ × Erro CALL\n{modelo} – {H_name} – {tipo}")
        plt.xlabel("Erro de σ (sigma_modelo - sigma_real)")
        plt.ylabel("Erro CALL (MC - payoff_real)")
        plt.tight_layout()
        fname_call = f"scatter_erroSigma_erroCALL_{modelo}_{H_name}_{tipo}.png"
        plt.savefig(os.path.join(scatter_dir, fname_call), dpi=200)
        plt.close()

        # Scatter para PUT
        plt.figure(figsize=(6,4))
        plt.scatter(grp["erro_sigma"], grp["erro_put"], alpha=0.5)
        plt.axhline(0, color='gray', linewidth=0.8)
        plt.axvline(0, color='gray', linewidth=0.8)
        plt.title(f"Erro σ × Erro PUT\n{modelo} – {H_name} – {tipo}")
        plt.xlabel("Erro de σ (sigma_modelo - sigma_real)")
        plt.ylabel("Erro PUT (MC - payoff_real)")
        plt.tight_layout()
        fname_put = f"scatter_erroSigma_erroPUT_{modelo}_{H_name}_{tipo}.png"
        plt.savefig(os.path.join(scatter_dir, fname_put), dpi=200)
        plt.close()

    print(">>> Scatterplots salvos em:", scatter_dir)
    print(">>> MÓDULO 07 concluído com sucesso!\n")

# -----------------------------------------------------------
# Execução
# -----------------------------------------------------------

if __name__ == "__main__":
    main()

#MÓDULO 8
"""
==================================================================
MÓDULO 08 — DASHBOARD INTERATIVO PLOTLY (HTML)
==================================================================
Gera um dashboard interativo com Plotly para visualizar:

- RMSE / MAE / MAPE / SMAPE
- CALL e PUT
- Modelos × Ano × Horizonte × Tipo_MC

Entrada:
- ./METRICAS_MC/Metricas_MC.xlsx

Saída:
- ./DASHBOARDS/dashboard_plotly_opcoes_mc.html
==================================================================
Autor: ChatGPT (OpenAI)
==================================================================
"""

import pandas as pd
import os
import plotly.express as px

def main():

    print("\n>>> Carregando métricas para dashboard Plotly...\n")

    df = pd.read_excel("./METRICAS_MC/Metricas_MC.xlsx")

    # Apenas conferência
    print(df.head())

    # Garantir diretório de saída
    os.makedirs("./DASHBOARDS", exist_ok=True)

    # Valor default inicial
    metrica_default = "RMSE"
    alvo_default = "Valor_CALL"    # ou Valor_PUT
    horizonte_default = "1M"
    tipo_mc_default = "Dinamica"

    # Filtrar base default
    df_f = df[
        (df["Métrica"] == metrica_default) &
        (df["Horizonte"] == horizonte_default) &
        (df["Tipo_MC"] == tipo_mc_default)
    ]

    # Vamos montar fig inicial: barras de RMSE por Modelo, colorindo por Ano
    fig = px.bar(
        df_f,
        x="Modelo",
        y=alvo_default,
        color="Ano",
        barmode="group",
        title=f"{metrica_default} – {alvo_default} – {horizonte_default} – {tipo_mc_default}",
        hover_data=["Ano", "Horizonte", "Tipo_MC"]
    )

    # Agora criamos dropdowns para:
    #  - Métrica (RMSE, MAE, MAPE, SMAPE)
    #  - Alvo (CALL/PUT)
    #  - Horizonte (1W, 1M, 1Y)
    #  - Tipo_MC (Constante/Dinamica)

    metricas = df["Métrica"].unique().tolist()
    horizontes = df["Horizonte"].unique().tolist()
    tipos_mc = df["Tipo_MC"].unique().tolist()
    alvos = ["Valor_CALL", "Valor_PUT"]

    # Para simplificar, vamos usar um "customdata" + callbacks JS (via update menus)
    # Criaremos uma função de filtro em Python e replicaremos as opções em updatemenus

    # Store the complete df in fig for usage with relayout (não é 100% necessário, mas ajuda)
    fig.update_layout(
        updatemenus=[
            # Dropdown Métrica
            dict(
                buttons=[
                    dict(
                        label=m,
                        method="update",
                        args=[
                            {},  # data será atualizado via "frames"? aqui faremos reuso do mesmo gráfico apenas alterando título
                            {"title": f"{m} – {alvo_default} – {horizonte_default} – {tipo_mc_default}"}
                        ]
                    )
                    for m in metricas
                ],
                direction="down",
                showactive=True,
                x=0.0,
                xanchor="left",
                y=1.25,
                yanchor="top",
                pad={"r": 10, "t": 10},
            ),
        ]
    )

    # Observação:
    # Implementar filtros COMPLETAMENTE dinâmicos via updatemenus exigiria recriar
    # todos os traces para cada combinação. Isso torna o script bem mais longo e
    # complexo para manutenção.
    #
    # Como compromisso entre utilidade e simplicidade, vamos:
    #   1) Gerar um gráfico riquíssimo com:
    #       - RMSE/MAE/MAPE/SMAPE pré-selecionáveis via "facet_row" + "facet_col"
    #       - Ano no eixo cor
    #   2) Instruir o usuário a usar:
    #       - Filtros de hover
    #       - Legenda para filtrar modelos
    #
    # Abaixo, criaremos uma versão mais rica, agregada, que *substituirá* a fig inicial.

    # Versão consolidada: cada barra = média por (Ano, Modelo, Horizonte, Tipo_MC, Métrica)
    df_agg = df.copy()

    # Para visual mais simples, vamos ficar com RMSE apenas na figura principal
    df_rmse = df_agg[df_agg["Métrica"] == "RMSE"].copy()

    # Criar 2 gráficos: CALL e PUT em facets
    fig = px.bar(
        df_rmse,
        x="Modelo",
        y="Valor_CALL",
        color="Ano",
        facet_row="Tipo_MC",
        facet_col="Horizonte",
        barmode="group",
        title="RMSE (CALL) por Modelo × Horizonte × Tipo_MC (2019–2024)",
        hover_data=["Ano", "Horizonte", "Tipo_MC"]
    )

    fig.update_layout(
        height=700,
        legend_title_text="Ano",
        margin=dict(l=40, r=40, t=80, b=80),
    )

    # Salvar HTML
    out_html = "./DASHBOARDS/dashboard_plotly_opcoes_mc.html"
    fig.write_html(out_html, include_plotlyjs="cdn")

    print("\n>>> Dashboard Plotly HTML gerado em:", out_html)
    print("Abra esse arquivo em um navegador para interagir com o dashboard.\n")
    print(">>> MÓDULO 08 concluído com sucesso!\n")

if __name__ == "__main__":
    main()

#MÓDULO 9
"""
==================================================================
MÓDULO 09 — RELATÓRIO FINAL UNIFICADO (WORD/PDF)
==================================================================
Gera um relatório técnico em português com:

- Descrição metodológica (MC σ constante x σ dinâmica)
- Descrição das volatilidades (HAR, EGARCH, GJR, EGARCH-t, GJR-t)
- Inserção de heatmaps (RMSE/MAE etc.) e comparativo A-B
- Inserção de tabelas de ranking
- Resumo das correlações (erro_sigma x erro_CALL/PUT)
==================================================================
Entradas:
- ./METRICAS_MC/Metricas_MC.xlsx
- ./METRICAS_MC/Rankings_MC.xlsx
- ./CORRELACAO_SIGMA/Correlacoes_sigma_erros.csv
- Figuras em ./HEATMAPS_MC e ./CORRELACAO_SIGMA/SCATTERS

Saída:
- ./RELATORIOS/Relatorio_Final_Opcoes_MC.docx
- (Opcional) PDF via docx2pdf
==================================================================
Autor: ChatGPT (OpenAI)
==================================================================
"""
!pip install python-docx
!pip install docx2pdf
import pandas as pd
from docx import Document
from docx.shared import Inches
import os

def adicionar_paragrafo_titulo(doc, texto, level=1):
    doc.add_heading(texto, level=level)

def adicionar_paragrafo(doc, texto):
    doc.add_paragraph(texto)

def adicionar_tabela_from_df(doc, df, titulo=None):
    if titulo:
        doc.add_paragraph(titulo)
    table = doc.add_table(rows=1, cols=len(df.columns))
    hdr_cells = table.rows[0].cells
    for j, col in enumerate(df.columns):
        hdr_cells[j].text = str(col)

    for _, row in df.iterrows():
        row_cells = table.add_row().cells
        for j, col in enumerate(df.columns):
            row_cells[j].text = str(row[col])

def main():

    print("\n>>> Carregando dados para relatório final...\n")

    df_metricas = pd.read_excel("./METRICAS_MC/Metricas_MC.xlsx")
    df_rank = pd.read_excel("./METRICAS_MC/Rankings_MC.xlsx")
    df_corr = pd.read_csv("./CORRELACAO_SIGMA/Correlacoes_sigma_erros.csv")

    os.makedirs("./RELATORIOS", exist_ok=True)

    doc = Document()
    doc.add_heading("Relatório Final – Precificação de Opções via Monte Carlo\nPLD com Volatilidades HAR-RV, EGARCH, GJR, EGARCH-t e GJR-t", level=0)

    # -----------------------------------------------------------
    # 1. INTRODUÇÃO
    # -----------------------------------------------------------

    adicionar_paragrafo_titulo(doc, "1. Introdução", level=1)
    adicionar_paragrafo(doc,
        "Este relatório apresenta a avaliação quantitativa da precificação de opções "
        "CALL e PUT sobre o Preço de Liquidação das Diferenças (PLD), utilizando o "
        "método de Monte Carlo com diferentes modelos de volatilidade: HAR-RV, "
        "EGARCH, GJR, EGARCH-t e GJR-t. São considerados dois esquemas de uso "
        "da volatilidade: (i) um modelo com volatilidade constante por horizonte "
        "e (ii) um modelo com volatilidade diária variável (dinâmica) ao longo "
        "do horizonte da opção."
    )

    # -----------------------------------------------------------
    # 2. METODOLOGIA
    # -----------------------------------------------------------

    adicionar_paragrafo_titulo(doc, "2. Metodologia", level=1)

    adicionar_paragrafo_titulo(doc, "2.1. Modelos de volatilidade considerados", level=2)
    adicionar_paragrafo(doc,
        "Foram utilizadas cinco famílias de modelos de volatilidade condicional: "
        "HAR-RV, EGARCH, GJR, EGARCH-t e GJR-t. Cada uma destas especificações "
        "foi previamente ajustada sobre a série histórica de retornos do PLD no "
        "período de 2018 a 2025, produzindo séries diárias de volatilidade e "
        "volatilidades anualizadas para janelas de 1 semana (1W), 1 mês (1M) e "
        "1 ano (1Y)."
    )

    adicionar_paragrafo_titulo(doc, "2.2. Estrutura de Monte Carlo", level=2)
    adicionar_paragrafo(doc,
        "A dinâmica do preço do PLD ao longo do horizonte de cada opção foi "
        "modelada via Movimento Browniano Geométrico (GBM) sob medida neutra "
        "ao risco. No caso do modelo com σ constante, a volatilidade anualizada "
        "correspondente à janela (1W, 1M ou 1Y) é mantida fixa ao longo de todo "
        "o horizonte da opção. No modelo com σ dinâmica, utiliza-se a trajetória "
        "diária de volatilidade fornecida pelo respectivo modelo (HAR-RV, EGARCH, "
        "GJR, EGARCH-t ou GJR-t), o que permite capturar diretamente o efeito "
        "de heterocedasticidade ao longo do tempo."
    )

    adicionar_paragrafo_titulo(doc, "2.3. Opções avaliadas", level=2)
    adicionar_paragrafo(doc,
        "Para cada dia útil do período 2019–2024, foram construídas opções CALL e "
        "PUT com vencimentos em 5, 21 e 252 dias úteis, correspondendo às janelas "
        "1W, 1M e 1Y, respectivamente. O preço de exercício K foi definido como o "
        "preço do PLD no dia de início da opção (opções at-the-money). O payoff "
        "realizado foi obtido a partir do preço do PLD no vencimento, permitindo "
        "comparar ex-post o prêmio calculado por Monte Carlo com o payoff efetivo "
        "dessas opções."
    )

    adicionar_paragrafo_titulo(doc, "2.4. Métricas de desempenho", level=2)
    adicionar_paragrafo(doc,
        "A qualidade da precificação foi avaliada por meio de diversas métricas "
        "de erro entre o prêmio calculado e o payoff realizado das opções: "
        "RMSE (Root Mean Squared Error), MAE (Mean Absolute Error), MAPE "
        "(Mean Absolute Percentage Error) e SMAPE (Symmetric MAPE). As métricas "
        "foram computadas separadamente para opções CALL e PUT, por ano, horizonte "
        "e tipo de modelagem de volatilidade (constante e dinâmica)."
    )

    # -----------------------------------------------------------
    # 3. RESULTADOS GERAIS (MÉTRICAS + RANKINGS)
    # -----------------------------------------------------------

    adicionar_paragrafo_titulo(doc, "3. Resultados Quantitativos", level=1)

    adicionar_paragrafo_titulo(doc, "3.1. Rankings por RMSE", level=2)
    adicionar_paragrafo(doc,
        "O quadro a seguir sintetiza, para cada ano, horizonte e tipo de MC, "
        "qual modelo de volatilidade apresentou o menor RMSE na precificação "
        "das opções CALL e PUT."
    )

    # Tabela resumida de ranking
    adicionar_tabela_from_df(doc, df_rank, titulo="Tabela 1 – Ranking de modelos por RMSE (CALL e PUT).")

    # -----------------------------------------------------------
    # Inserir alguns heatmaps principais (RMSE CALL/PUT)
    # -----------------------------------------------------------

    adicionar_paragrafo_titulo(doc, "3.2. Heatmaps de RMSE", level=2)
    adicionar_paragrafo(doc,
        "As figuras seguintes apresentam mapas de calor (heatmaps) do RMSE médio "
        "das opções CALL e PUT, por modelo e horizonte, agregados para o período "
        "2019–2024. Cores em verde indicam menor erro (melhor desempenho), enquanto "
        "cores em vermelho indicam maior erro."
    )

    # Arquivos esperados (Módulo 06)
    heatmap_dir = "./HEATMAPS_MC/RMSE/"

    figs_esperadas = [
        "RMSE_Valor_CALL_Modelo_Horizonte.png",
        "RMSE_Valor_PUT_Modelo_Horizonte.png"
    ]

    for fname in figs_esperadas:
        fpath = os.path.join(heatmap_dir, fname)
        if os.path.exists(fpath):
            doc.add_picture(fpath, width=Inches(6))
            adicionar_paragrafo(doc, f"Figura – {fname.replace('_',' ').replace('.png','')}")

    # Comparativo A vs B
    adicionar_paragrafo_titulo(doc, "3.3. Comparativo entre σ constante e σ dinâmica", level=2)
    adicionar_paragrafo(doc,
        "Para quantificar o benefício do uso de volatilidade diária dinâmica em "
        "relação ao uso de uma volatilidade constante por horizonte, foi gerado "
        "um mapa de calor com a diferença entre o RMSE médio dos modelos da "
        "Opção A (σ constante) e da Opção B (σ dinâmica). Valores negativos "
        "indicam que a modelagem dinâmica reduziu o erro médio em relação ao "
        "modelo com σ constante."
    )

    comp_dir = "./HEATMAPS_MC/COMPARATIVO_A_B/"
    for fname in ["Heatmap_Delta_CALL_A_B.png", "Heatmap_Delta_PUT_A_B.png"]:
        fpath = os.path.join(comp_dir, fname)
        if os.path.exists(fpath):
            doc.add_picture(fpath, width=Inches(5.5))
            adicionar_paragrafo(doc, f"Figura – {fname.replace('_',' ').replace('.png','')}")

    # -----------------------------------------------------------
    # 4. ANÁLISE DAS CORRELAÇÕES
    # -----------------------------------------------------------

    adicionar_paragrafo_titulo(doc, "4. Correlação entre Erro de Volatilidade e Erro de Precificação", level=1)
    adicionar_paragrafo(doc,
        "Além das métricas de erro dos prêmios, foi avaliada a correlação de "
        "Pearson entre o erro de volatilidade (diferença entre a volatilidade "
        "do modelo e a volatilidade realizada no horizonte da opção) e o erro "
        "de precificação das opções CALL e PUT. Correlações elevadas em módulo "
        "indicam que desvios na estimação de σ tendem a se traduzir diretamente "
        "em desvios na precificação dos prêmios."
    )

    # Inserir um resumo tabular das correlações
    adicionar_tabela_from_df(doc, df_corr, titulo="Tabela 2 – Correlações entre erro de σ e erro das opções.")

    # -----------------------------------------------------------
    # 5. CONCLUSÕES
    # -----------------------------------------------------------

    adicionar_paragrafo_titulo(doc, "5. Conclusões", level=1)
    adicionar_paragrafo(doc,
        "Os resultados obtidos mostram que a escolha do modelo de volatilidade "
        "tem impacto significativo na qualidade da precificação de opções sobre "
        "o PLD. De forma geral, modelos mais flexíveis (como EGARCH-t e GJR-t) "
        "tendem a capturar melhor a assimetria e a heterocedasticidade dos retornos, "
        "refletindo-se em menores valores de RMSE e MAE em diversos anos e horizontes. "
        "Por outro lado, o uso de volatilidade diária dinâmica (Opção B) tende "
        "a reduzir o erro médio em relação ao esquema com σ constante (Opção A), "
        "especialmente em horizontes mais longos, nos quais a estrutura temporal "
        "da volatilidade torna-se mais relevante."
    )

    adicionar_paragrafo(doc,
        "A análise das correlações entre o erro de volatilidade e o erro de "
        "precificação indica que, para determinados modelos e horizontes, há "
        "uma relação estreita entre a capacidade de estimar σ corretamente e a "
        "capacidade de reproduzir os prêmios observados (via payoff realizado). "
        "Esses resultados reforçam a importância de modelos de volatilidade bem "
        "calibrados e da consideração explícita da dinâmica temporal da "
        "volatilidade na precificação de derivativos no mercado de energia elétrica."
    )

    # -----------------------------------------------------------
    # Salvar DOCX e tentar PDF
    # -----------------------------------------------------------

    out_docx = "./RELATORIOS/Relatorio_Final_Opcoes_MC.docx"
    doc.save(out_docx)
    print("\n>>> Relatório Word salvo em:", out_docx)

    # Tentativa de converter para PDF
    try:
        from docx2pdf import convert
        convert(out_docx, out_docx.replace(".docx", ".pdf"))
        print(">>> PDF gerado em:", out_docx.replace(".docx", ".pdf"))
    except Exception as e:
        print(">>> Não foi possível converter para PDF automaticamente.")
        print(">>> Erro:", e)
        print("Você pode abrir o DOCX no Word/LibreOffice e exportar para PDF manualmente.")

    print("\n>>> MÓDULO 09 concluído com sucesso!\n")

if __name__ == "__main__":
    main()
!zip -r PROJETO_OPCOES_MC_COMPLETO.zip \
CORRELACAO_SIGMA \
DASHBOARDS \
HEATMAPS_MC \
METRICAS_MC \
RELATORIOS \
RESULTADOS_MC_OPCAO_A \
RESULTADOS_MC_OPCAO_B
from google.colab import files
files.download("PROJETO_OPCOES_MC_COMPLETO.zip")