# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WY3CTO6mnoh6ZWPZwbXDQSDDaGHKfRdr
"""

import pandas as pd, numpy as np, os, math, warnings, re
from datetime import datetime

path = "/content/PREÇO MEDIO DIÁRIO PLD CONTÍNUO VERTICAL PERÍODO  17-04-18 A 03-06-25 (PER TOTAL).xlsx"
df_raw = pd.read_excel(path)
df_raw.head(), df_raw.columns[:10], df_raw.shape

# Prepare dataframe
df = df_raw.rename(columns={
    'DATA SUBMERCADO SUDESTE': 'data',
    'PREÇO MEDIO DIÁRIO': 'preco'
}).copy()

df['data'] = pd.to_datetime(df['data'])
df = df.sort_values('data').reset_index(drop=True)

# log returns
df['retorno_log'] = np.log(df['preco'] / df['preco'].shift(1))
# realized daily vol proxy
df['vol_realizada'] = df['retorno_log'].abs()

df.head(), df.tail(), df.isna().sum()

import importlib, sys, textwrap, statistics

!pip install arch
import arch, arch.univariate
arch.__version__

import numpy as np, pandas as pd, math, warnings
from scipy.optimize import minimize
from scipy.special import gammaln

# Prepare returns series (drop first NA)
r = df['retorno_log'].dropna().to_numpy()
dates_r = df.loc[df['retorno_log'].notna(), 'data'].to_numpy()

def t_logpdf_standardized(z, nu):
    """
    Log-pdf of standardized Student-t with df=nu, mean 0, variance 1.
    If T ~ t_nu (standard), var(T)=nu/(nu-2). Define Z=T/s with s=sqrt(nu/(nu-2)).
    """
    s = math.sqrt(nu/(nu-2.0))
    t = z * s  # back-transform
    # log pdf of standard t at t
    # f_T(t) = gamma((nu+1)/2)/(sqrt(nu*pi)*gamma(nu/2))*(1+t^2/nu)^(-(nu+1)/2)
    logc = gammaln((nu+1)/2.0) - (0.5*math.log(nu*math.pi) + gammaln(nu/2.0))
    log_kernel = -((nu+1)/2.0)*np.log1p((t*t)/nu)
    # change of variables: f_Z(z)=f_T(t)*|dt/dz|=f_T(z*s)*s
    return logc + log_kernel + math.log(s)

def expected_abs_z(nu):
    """
    E|Z| for standardized Student-t with df=nu.
    E|T| for standard t:
    E|T| = 2*sqrt(nu)*Gamma((nu+1)/2)/(sqrt(pi)*(nu-1)*Gamma(nu/2)), nu>1
    Then divide by s to standardize variance to 1.
    """
    if nu <= 2.0:
        return np.nan
    log_num = math.log(2.0) + 0.5*math.log(nu) + gammaln((nu+1)/2.0)
    log_den = 0.5*math.log(math.pi) + math.log(nu-1.0) + gammaln(nu/2.0)
    E_abs_T = math.exp(log_num - log_den)
    s = math.sqrt(nu/(nu-2.0))
    return E_abs_T / s

def egarch_recursion(params, r):
    mu, omega, alpha, gamma, beta, nu = params
    n = len(r)
    eps = r - mu
    # initialize using sample variance
    init_var = np.var(eps) if np.var(eps) > 1e-12 else 1e-12
    logh = np.empty(n)
    h = np.empty(n)
    logh0 = math.log(init_var)
    logh[0] = logh0
    h[0] = math.exp(logh[0])
    Eabs = expected_abs_z(nu)
    if not np.isfinite(Eabs):
        return None, None, None
    # Recursion: log(h_t) = omega + alpha*(|z_{t-1}|-E|z|) + gamma*z_{t-1} + beta*log(h_{t-1})
    # Here h_t = sigma_t^2, so sigma_t = sqrt(h_t)
    for t in range(1, n):
        z_prev = eps[t-1] / math.sqrt(h[t-1])
        logh[t] = omega + alpha*(abs(z_prev) - Eabs) + gamma*z_prev + beta*logh[t-1]
        # Guard against overflow/underflow
        logh[t] = float(np.clip(logh[t], -50, 50))
        h[t] = math.exp(logh[t])
    sigma = np.sqrt(h)
    z = eps / sigma
    return sigma, z, eps

def neg_loglik(params, r):
    mu, omega, alpha, gamma, beta, nu = params
    # constraints via penalties (bounds also used)
    if alpha < 0 or beta <= 0 or beta >= 0.999 or nu <= 2.05:
        return 1e12
    sigma, z, eps = egarch_recursion(params, r)
    if sigma is None:
        return 1e12
    # log-likelihood: sum [log f_Z(z_t) - log sigma_t]
    ll = t_logpdf_standardized(z, nu) - np.log(sigma)
    if not np.all(np.isfinite(ll)):
        return 1e12
    return -float(np.sum(ll))

# Initial guesses
mu0 = np.mean(r)
omega0 = math.log(np.var(r)) * (1-0.95)  # rough
alpha0 = 0.1
gamma0 = 0.0
beta0 = 0.95
nu0 = 8.0

x0 = np.array([mu0, omega0, alpha0, gamma0, beta0, nu0], dtype=float)
bounds = [
    (None, None),           # mu
    (None, None),           # omega
    (1e-6, 5.0),            # alpha
    (-5.0, 5.0),            # gamma
    (1e-6, 0.999),          # beta
    (2.05, 200.0)           # nu
]

warnings.filterwarnings("ignore")
res = minimize(neg_loglik, x0, args=(r,), method="L-BFGS-B", bounds=bounds, options={"maxiter": 2000})
res.success, res.message, res.fun, res.x

params_hat = res.x
sigma, z, eps = egarch_recursion(params_hat, r)

# Build output dataframe aligned to original df
out = df.copy()
out['vol_EGARCHt_diaria'] = np.nan
out.loc[out['retorno_log'].notna(), 'vol_EGARCHt_diaria'] = sigma

# Horizons (non-annualized cumulative vols, in decimal)
sqrt5, sqrt21, sqrt252 = math.sqrt(5), math.sqrt(21), math.sqrt(252)
out['vol_EGARCHt_1W'] = out['vol_EGARCHt_diaria'] * sqrt5
out['vol_EGARCHt_1M'] = out['vol_EGARCHt_diaria'] * sqrt21
out['vol_EGARCHt_1Y'] = out['vol_EGARCHt_diaria'] * sqrt252  # annualized over 252

# Annualized versions from horizon vols
out['vol_EGARCHt_1W_anualizada'] = out['vol_EGARCHt_1W'] * math.sqrt(252/5)
out['vol_EGARCHt_1M_anualizada'] = out['vol_EGARCHt_1M'] * math.sqrt(252/21)
out['vol_EGARCHt_1Y_anualizada'] = out['vol_EGARCHt_1Y']  # already annualized by construction

# Reorder/rename requested columns
final = out[['data','preco','retorno_log','vol_realizada',
             'vol_EGARCHt_diaria','vol_EGARCHt_1W','vol_EGARCHt_1M','vol_EGARCHt_1Y',
             'vol_EGARCHt_1W_anualizada','vol_EGARCHt_1M_anualizada','vol_EGARCHt_1Y_anualizada']].copy()

final.head(10), final.tail(3)

from openpyxl import Workbook
from openpyxl.utils.dataframe import dataframe_to_rows
from openpyxl.styles import Font, Alignment, PatternFill
from openpyxl.worksheet.table import Table, TableStyleInfo

out_path = "/content/PLD_volatilidades_EGARCHt_1W_1M_1Y.xlsx"

wb = Workbook()
ws = wb.active
ws.title = "EGARCH-t"

# Write dataframe
for r_i, row in enumerate(dataframe_to_rows(final, index=False, header=True), start=1):
    ws.append(row)

# Style header
header_fill = PatternFill("solid", fgColor="1F4E79")
header_font = Font(color="FFFFFF", bold=True)
for cell in ws[1]:
    cell.fill = header_fill
    cell.font = header_font
    cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)

# Set column widths and formats
col_formats = {
    "A": "yyyy-mm-dd",
    "B": "#,##0.00",
    "C": "0.000000",
    "D": "0.000000",
    "E": "0.000000",
    "F": "0.000000",
    "G": "0.000000",
    "H": "0.000000",
    "I": "0.000000",
    "J": "0.000000",
    "K": "0.000000",
}
col_widths = {
    "A": 12, "B": 16, "C": 14, "D": 16, "E": 18,
    "F": 16, "G": 16, "H": 16, "I": 22, "J": 22, "K": 22
}

for col, width in col_widths.items():
    ws.column_dimensions[col].width = width
    for cell in ws[col][1:]:  # skip header
        cell.number_format = col_formats.get(col, "General")

# Freeze panes
ws.freeze_panes = "A2"

# Add table style
table_ref = f"A1:K{ws.max_row}"
tab = Table(displayName="TabelaEGARCHt", ref=table_ref)
style = TableStyleInfo(name="TableStyleMedium9", showFirstColumn=False,
                       showLastColumn=False, showRowStripes=True, showColumnStripes=False)
tab.tableStyleInfo = style
ws.add_table(tab)

# Add a small "Parametros" sheet with estimated params
ws2 = wb.create_sheet("Parametros")
ws2.append(["Parâmetro", "Valor estimado"])
for cell in ws2[1]:
    cell.fill = header_fill
    cell.font = header_font
    cell.alignment = Alignment(horizontal="center", vertical="center")
param_names = ["mu", "omega", "alpha", "gamma", "beta", "nu (t)"]
for name, val in zip(param_names, params_hat):
    ws2.append([name, float(val)])
ws2.column_dimensions["A"].width = 14
ws2.column_dimensions["B"].width = 18
for cell in ws2["B"][1:]:
    cell.number_format = "0.000000"

ws2.freeze_panes = "A2"

wb.save(out_path)
out_path